config/routes.rb
Connectedin::Application.routes.draw do
  root 'students#show_all'
  get "students" => "students#show_all", as: 'show_all'

  # get 'students/nick' => 'students#show_nick', as: 'nick_student'
  get 'nick' => 'students#show_nick', as: 'nick_student'
  get 'fremen' => 'students#show_fremen', as: 'fremen_student'
  get 'yasmin' => 'students#show_yasmin', as: 'yasmin_student'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show_all
  end

  def show_nick
    @student = {
        name: "Nick Smith",
        city: "El Paso",
        description: "Friendliest Wanksta Bro",
        picture_url: "http://placekitten.com/g/100/100"
    }
  end

  def show_yasmin
    @student = {
        name: "Yasmin Fazelina",
        city: "Austin",
        description: "Amazing hair",
        picture_url: "http://placekitten.com/g/200/200"
    }
  end

  def show_fremen
    @student = {
        name: "Fremen Deruvo",
        city: "Austin",
        description: "Funny guy, cool glasses",
        picture_url: "http://placekitten.com/g/300/300"
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connectedin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/show_all.html.erb
<h1>ConnectedIn</h1>

<ul> <h3>fronds</h3>
  <li><%= link_to "Nick", "nick" %></li>
  <li><%= link_to "Yasmin", "yasmin" %></li>
  <li><%= link_to "Fremen", "fremen" %></li>
</ul>

app/views/students/show_fremen.html.erb
<h1><%= @student[:name] %></h1>
<p><%= @student[:description] %></p>
<p><%= @student[:city] %></p>
<p><%= image_tag(@student[:picture_url]) %></p>


<%= link_to "Back", show_all_path %>

app/views/students/show_nick.html.erb
<h1><%= @student[:name] %></h1>
<p><%= @student[:description] %></p>
<p><%= @student[:city] %></p>
<p><%= image_tag(@student[:picture_url]) %></p>


<%= link_to "Back", show_all_path %>

app/views/students/show_yasmin.html.erb
<h1><%= @student[:name] %></h1>
<p><%= @student[:description] %></p>
<p><%= @student[:city] %></p>
<p><%= image_tag(@student[:picture_url]) %></p>


<%= link_to "Back", show_all_path %>